/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package globalharmony.app;

import globalharmony.util.GlobalData;
import java.beans.PropertyVetoException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;


/**
 *
 * @author ozumc
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    
    LoginForm loginForm = new LoginForm();
    AddSongsForm addSongsForm = new AddSongsForm();
    ViewSongsForm viewSongsForm = new ViewSongsForm();
    
    Map <String, JInternalFrame> forms = new HashMap<>();
    
    public MainForm() {
        initComponents();
        forms.put("loginForm", loginForm);
        forms.put("addSongsForm", addSongsForm);
        forms.put("viewSongsForm", viewSongsForm);
        
        forms.keySet().forEach(key->{
            jDesktopPane1.add(forms.get(key));
        });
    }
    

    
    private void showForm(String name, boolean checkLogin){
        if (checkLogin && GlobalData.stf == null) {
            //Check for authorization here
            showForm("loginForm", false);
        } else {
            try {
                if (forms.get(name).isClosed()) {
                    forms.put(name,forms.get(name).getClass().newInstance());
                    jDesktopPane1.add(forms.get(name));
                }
                forms.get(name).show();
                forms.get(name).setSelected(true);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }
    
    private void showForm(String frmName) {
        showForm(frmName, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFileMenu = new javax.swing.JMenu();
        jMenuItemLogin = new javax.swing.JMenuItem();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jManageMenu = new javax.swing.JMenu();
        jSongMenu = new javax.swing.JMenu();
        jMenuItemStudentAdd = new javax.swing.JMenuItem();
        jMenuItemStudentDelete = new javax.swing.JMenuItem();
        jMenuItemStudentUpdate = new javax.swing.JMenuItem();
        jMenuItemStudentView = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jFileMenu.setText("File");

        jMenuItemLogin.setText("Login");
        jMenuItemLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoginActionPerformed(evt);
            }
        });
        jFileMenu.add(jMenuItemLogin);

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jFileMenu.add(jMenuItemLogout);

        jMenuItemExit.setText("Exit");
        jFileMenu.add(jMenuItemExit);

        jMenuBar1.add(jFileMenu);

        jManageMenu.setText("Manage");

        jSongMenu.setText("Song");

        jMenuItemStudentAdd.setText("Add");
        jMenuItemStudentAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStudentAddActionPerformed(evt);
            }
        });
        jSongMenu.add(jMenuItemStudentAdd);

        jMenuItemStudentDelete.setText("Delete");
        jMenuItemStudentDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStudentDeleteActionPerformed(evt);
            }
        });
        jSongMenu.add(jMenuItemStudentDelete);

        jMenuItemStudentUpdate.setText("Update");
        jMenuItemStudentUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStudentUpdateActionPerformed(evt);
            }
        });
        jSongMenu.add(jMenuItemStudentUpdate);

        jMenuItemStudentView.setText("View");
        jMenuItemStudentView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStudentViewActionPerformed(evt);
            }
        });
        jSongMenu.add(jMenuItemStudentView);

        jManageMenu.add(jSongMenu);

        jMenuBar1.add(jManageMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        //showForm("addSongsForm");
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItemStudentAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStudentAddActionPerformed
        showForm("addSongsForm");
    }//GEN-LAST:event_jMenuItemStudentAddActionPerformed

    private void jMenuItemStudentDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStudentDeleteActionPerformed
        //showForm("addSongsForm");
    }//GEN-LAST:event_jMenuItemStudentDeleteActionPerformed

    private void jMenuItemStudentUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStudentUpdateActionPerformed
        //showForm("addSongsForm");
    }//GEN-LAST:event_jMenuItemStudentUpdateActionPerformed

    private void jMenuItemStudentViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStudentViewActionPerformed
        showForm("viewSongsForm");
    }//GEN-LAST:event_jMenuItemStudentViewActionPerformed

    private void jMenuItemLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoginActionPerformed
        showForm("loginForm");
    }//GEN-LAST:event_jMenuItemLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jFileMenu;
    private javax.swing.JMenu jManageMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLogin;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemStudentAdd;
    private javax.swing.JMenuItem jMenuItemStudentDelete;
    private javax.swing.JMenuItem jMenuItemStudentUpdate;
    private javax.swing.JMenuItem jMenuItemStudentView;
    private javax.swing.JMenu jSongMenu;
    // End of variables declaration//GEN-END:variables



}
